#
# Module manifest for module 'YourModuleName'
#
# Generated by: YourName
#
# Generated on: (Date)
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'YourModuleName.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Desktop', 'Core'

# ID used to uniquely identify this module
GUID = '1c11ab51-4c1e-1111-8a1a-1f1c6f111db1'

# Author of this module
Author = 'YourName'

# Company or vendor of this module
CompanyName = 'YourCompanyName'

# Copyright statement for this module
Copyright = 'Copyright (c) your copyright year by YourCompanyName'

# Description of the functionality provided by this module
Description = 'Description of what your module does'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all files packaged with this module
FileList = @('YourModuleName.psm1')

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{
    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Tag1', 'Tag2')

        # License URI for this module
        LicenseUri = 'http://yourlicenseuri.com'

        # Project URI for this module
        ProjectUri = 'http://yourprojecturi.com'

        # Icon URI for this module
        IconUri = 'http://youriconuri.com'

        # Release notes for this module
        ReleaseNotes = 'Release notes for your module here.'
        
        # Prerelease string of this module
        Prerelease = 'Alpha'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
